file_name = ['./in/',problem,'.nc'];
ncid      =    netcdf.create(file_name,'NC_SHARE');
imx       =    netcdf.defDim(ncid,'im',im);     jmy       =    netcdf.defDim(ncid,'jm',jm);
kbz       =    netcdf.defDim(ncid,'kb',kb);     dconst    =    netcdf.defDim(ncid,'dc',1);
zid       =    netcdf.defVar(ncid,'z','double',[dconst dconst kbz]);
zzid      =    netcdf.defVar(ncid,'zz','double',[dconst dconst kbz]);
dxid      =    netcdf.defVar(ncid,'dx','double',[imx jmy dconst]);
dyid      =    netcdf.defVar(ncid,'dy','double',[imx jmy dconst]);
corid     =    netcdf.defVar(ncid,'cor','double',[imx jmy dconst]);
hid       =    netcdf.defVar(ncid,'h','double',[imx jmy dconst]);
fsmid     =    netcdf.defVar(ncid,'fsm','double',[imx jmy dconst]);
dumid     =    netcdf.defVar(ncid,'dum','double',[imx jmy dconst]);
dvmid     =    netcdf.defVar(ncid,'dvm','double',[imx jmy dconst]);
tbid     =    netcdf.defVar(ncid,'tb','double',[imx jmy kbz]);
sbid     =    netcdf.defVar(ncid,'sb','double',[imx jmy kbz]);
tclimid  =    netcdf.defVar(ncid,'tclim','double',[imx jmy kbz]);
sclimid  =    netcdf.defVar(ncid,'sclim','double',[imx jmy kbz]);
rhoid   =    netcdf.defVar(ncid,'rho','double',[imx jmy kbz]);
rmeanid   =    netcdf.defVar(ncid,'rmean','double',[imx jmy kbz]);
dzid      =    netcdf.defVar(ncid,'dz','double',[dconst dconst kbz]);
dzzid     =    netcdf.defVar(ncid,'dzz','double',[dconst dconst kbz]);
artid     =    netcdf.defVar(ncid,'art','double',[imx jmy dconst]);
aruid     =    netcdf.defVar(ncid,'aru','double',[imx jmy dconst]);
arvid     =    netcdf.defVar(ncid,'arv','double',[imx jmy dconst]);
ubid     =    netcdf.defVar(ncid,'ub','double',[imx jmy kbz]);
vbid     =    netcdf.defVar(ncid,'vb','double',[imx jmy kbz]);
uabid     =    netcdf.defVar(ncid,'uab','double',[imx jmy dconst]);
vabid     =    netcdf.defVar(ncid,'vab','double',[imx jmy dconst]);
elbid     =    netcdf.defVar(ncid,'elb','double',[imx jmy dconst]);
etbid     =    netcdf.defVar(ncid,'etb','double',[imx jmy dconst]);
rnid     =    netcdf.defVar(ncid,'rn','double',[dconst dconst dconst]);
rsid     =    netcdf.defVar(ncid,'rs','double',[dconst dconst dconst]);
hmaxid     =    netcdf.defVar(ncid,'hmax','double',[dconst dconst dconst]);
ssurfid    =    netcdf.defVar(ncid,'ssurf','double',[imx jmy dconst]);
tsurfid    =    netcdf.defVar(ncid,'tsurf','double',[imx jmy dconst]);
netcdf.endDef(ncid)

netcdf.putVar(ncid,zid,z);              netcdf.putVar(ncid,zzid,zz);
netcdf.putVar(ncid,dxid,dx);            netcdf.putVar(ncid,dyid,dy);
netcdf.putVar(ncid,corid,cor);          netcdf.putVar(ncid,hid,h);
netcdf.putVar(ncid,fsmid,fsm);          netcdf.putVar(ncid,dumid,dum);          
netcdf.putVar(ncid,dvmid,dvm);          netcdf.putVar(ncid,tbid,tb);              
netcdf.putVar(ncid,sbid,sb);            netcdf.putVar(ncid,tclimid,tclim);        
netcdf.putVar(ncid,sclimid,sclim);      netcdf.putVar(ncid,dzid,dz);
netcdf.putVar(ncid,dzzid,dzz);           netcdf.putVar(ncid,artid,art);
netcdf.putVar(ncid,aruid,aru);           netcdf.putVar(ncid,arvid,arv);
netcdf.putVar(ncid,ubid,ub);             netcdf.putVar(ncid,vbid,vb);
netcdf.putVar(ncid,uabid,uab);           netcdf.putVar(ncid,vabid,vab);
netcdf.putVar(ncid,elbid,elb);           netcdf.putVar(ncid,etbid,etb);  
netcdf.putVar(ncid,rnid,rn);             netcdf.putVar(ncid,rsid,rs);  
netcdf.putVar(ncid,ssurfid,ssurf);       netcdf.putVar(ncid,tsurfid,tsurf);       
netcdf.putVar(ncid,rhoid,rho);           netcdf.putVar(ncid,rmeanid,rmean);
netcdf.putVar(ncid,hmaxid,hmax);

netcdf.close(ncid);